// extend module moment cho zjs
;(function(window, zjs){

// moment.js
// version : 2.10.3
// authors : Tim Wood, Iskren Chernev, Moment.js contributors
// license : MIT
// momentjs.com
(function(g,H){g.moment=H()})(this,function(){function g(){return gb.apply(null,arguments)}function H(a){return a instanceof Array||"[object Array]"===Object.prototype.toString.call(a)}function pa(a){return null!=a&&"[object Object]"===Object.prototype.toString.call(a)}function da(a){return"number"===typeof a||"[object Number]"===Object.prototype.toString.call(a)}function qa(a){return a instanceof Date||"[object Date]"===Object.prototype.toString.call(a)}function hb(a,b){var c=[],d;for(d=0;d<a.length;++d)c.push(b(a[d],
d));return c}function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function P(a,b){for(var c in b)u(b,c)&&(a[c]=b[c]);u(b,"toString")&&(a.toString=b.toString);u(b,"valueOf")&&(a.valueOf=b.valueOf);return a}function I(a,b,c,d){return ib(a,b,c,d,!0).utc()}function n(a){null==a._pf&&(a._pf={empty:!1,unusedTokens:[],unusedInput:[],overflow:-2,charsLeftOver:0,nullInput:!1,invalidMonth:null,invalidFormat:!1,userInvalidated:!1,iso:!1,parsedDateParts:[],meridiem:null});return a._pf}function Ha(a){if(null==
a._isValid){var b=n(a),c=Wb.call(b.parsedDateParts,function(a){return null!=a}),c=!isNaN(a._d.getTime())&&0>b.overflow&&!b.empty&&!b.invalidMonth&&!b.invalidWeekday&&!b.nullInput&&!b.invalidFormat&&!b.userInvalidated&&(!b.meridiem||b.meridiem&&c);a._strict&&(c=c&&0===b.charsLeftOver&&0===b.unusedTokens.length&&void 0===b.bigHour);if(null!=Object.isFrozen&&Object.isFrozen(a))return c;a._isValid=c}return a._isValid}function ra(a){var b=I(NaN);null!=a?P(n(b),a):n(b).userInvalidated=!0;return b}function A(a){return void 0===
a}function Ia(a,b){var c,d,f;A(b._isAMomentObject)||(a._isAMomentObject=b._isAMomentObject);A(b._i)||(a._i=b._i);A(b._f)||(a._f=b._f);A(b._l)||(a._l=b._l);A(b._strict)||(a._strict=b._strict);A(b._tzm)||(a._tzm=b._tzm);A(b._isUTC)||(a._isUTC=b._isUTC);A(b._offset)||(a._offset=b._offset);A(b._pf)||(a._pf=n(b));A(b._locale)||(a._locale=b._locale);if(0<Ja.length)for(c in Ja)d=Ja[c],f=b[d],A(f)||(a[d]=f);return a}function ja(a){Ia(this,a);this._d=new Date(null!=a._d?a._d.getTime():NaN);this.isValid()||
(this._d=new Date(NaN));!1===Ka&&(Ka=!0,g.updateOffset(this),Ka=!1)}function Q(a){return a instanceof ja||null!=a&&null!=a._isAMomentObject}function B(a){return 0>a?Math.ceil(a)||0:Math.floor(a)}function l(a){a=+a;var b=0;0!==a&&isFinite(a)&&(b=B(a));return b}function jb(a,b,c){var d=Math.min(a.length,b.length),f=Math.abs(a.length-b.length),R=0,e;for(e=0;e<d;e++)(c&&a[e]!==b[e]||!c&&l(a[e])!==l(b[e]))&&R++;return R+f}function kb(a){!1===g.suppressDeprecationWarnings&&"undefined"!==typeof console&&
console.warn&&console.warn("Deprecation warning: "+a)}function C(a,b){var c=!0;return P(function(){null!=g.deprecationHandler&&g.deprecationHandler(null,a);if(c){for(var d=[],f,R=0;R<arguments.length;R++){f="";if("object"===typeof arguments[R]){f+="\n["+R+"] ";for(var e in arguments[0])f+=e+": "+arguments[0][e]+", ";f=f.slice(0,-2)}else f=arguments[R];d.push(f)}kb(a+"\nArguments: "+Array.prototype.slice.call(d).join("")+"\n"+Error().stack);c=!1}return b.apply(this,arguments)},b)}function lb(a,b){null!=
g.deprecationHandler&&g.deprecationHandler(a,b);mb[a]||(kb(b),mb[a]=!0)}function K(a){return a instanceof Function||"[object Function]"===Object.prototype.toString.call(a)}function nb(a,b){var c=P({},a),d;for(d in b)u(b,d)&&(pa(a[d])&&pa(b[d])?(c[d]={},P(c[d],a[d]),P(c[d],b[d])):null!=b[d]?c[d]=b[d]:delete c[d]);for(d in a)u(a,d)&&!u(b,d)&&pa(a[d])&&(c[d]=P({},c[d]));return c}function La(a){null!=a&&this.set(a)}function z(a,b){var c=a.toLowerCase();ka[c]=ka[c+"s"]=ka[b]=a}function D(a){return"string"===
typeof a?ka[a]||ka[a.toLowerCase()]:void 0}function Ma(a){var b={},c,d;for(d in a)u(a,d)&&(c=D(d))&&(b[c]=a[d]);return b}function Xb(a){var b=[],c;for(c in a)b.push({unit:c,priority:y[c]});b.sort(function(a,b){return a.priority-b.priority});return b}function ea(a,b){return function(c){if(null!=c){if(this.isValid())this._d["set"+(this._isUTC?"UTC":"")+a](c);g.updateOffset(this,b);return this}return sa(this,a)}}function sa(a,b){return a.isValid()?a._d["get"+(a._isUTC?"UTC":"")+b]():NaN}function L(a,
b,c){var d=""+Math.abs(a);return(0<=a?c?"+":"":"-")+Math.pow(10,Math.max(0,b-d.length)).toString().substr(1)+d}function k(a,b,c,d){var f=d;"string"===typeof d&&(f=function(){return this[d]()});a&&(fa[a]=f);b&&(fa[b[0]]=function(){return L(f.apply(this,arguments),b[1],b[2])});c&&(fa[c]=function(){return this.localeData().ordinal(f.apply(this,arguments),a)})}function Yb(a){return a.match(/\[[\s\S]/)?a.replace(/^\[|\]$/g,""):a.replace(/\\/g,"")}function Zb(a){var b=a.match(ob),c,d;c=0;for(d=b.length;c<
d;c++)b[c]=fa[b[c]]?fa[b[c]]:Yb(b[c]);return function(c){var f="",e;for(e=0;e<d;e++)f+=b[e]instanceof Function?b[e].call(c,a):b[e];return f}}function Na(a,b){if(!a.isValid())return a.localeData().invalidDate();b=pb(b,a.localeData());Oa[b]=Oa[b]||Zb(b);return Oa[b](a)}function pb(a,b){function c(a){return b.longDateFormat(a)||a}var d=5;for(ta.lastIndex=0;0<=d&&ta.test(a);)a=a.replace(ta,c),ta.lastIndex=0,--d;return a}function h(a,b,c){Pa[a]=K(b)?b:function(a,f){return a&&c?c:b}}function $b(a,b){return u(Pa,
a)?Pa[a](b._strict,b._locale):new RegExp(ac(a))}function ac(a){return Y(a.replace("\\","").replace(/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g,function(a,c,d,f,e){return c||d||f||e}))}function Y(a){return a.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}function q(a,b){var c,d=b;"string"===typeof a&&(a=[a]);da(b)&&(d=function(a,c){c[b]=l(a)});for(c=0;c<a.length;c++)Qa[a[c]]=d}function la(a,b){q(a,function(a,d,f,e){f._w=f._w||{};b(a,f._w,f,e)})}function Ra(a,b){return(new Date(Date.UTC(a,b+1,0))).getUTCDate()}
function qb(a,b){var c;if(!a.isValid())return a;if("string"===typeof b)if(/^\d+$/.test(b))b=l(b);else if(b=a.localeData().monthsParse(b),!da(b))return a;c=Math.min(a.date(),Ra(a.year(),b));a._d["set"+(a._isUTC?"UTC":"")+"Month"](b,c);return a}function rb(a){return null!=a?(qb(this,a),g.updateOffset(this,!0),this):sa(this,"Month")}function sb(){function a(a,b){return b.length-a.length}var b=[],c=[],d=[],f,e;for(f=0;12>f;f++)e=I([2E3,f]),b.push(this.monthsShort(e,"")),c.push(this.months(e,"")),d.push(this.months(e,
"")),d.push(this.monthsShort(e,""));b.sort(a);c.sort(a);d.sort(a);for(f=0;12>f;f++)b[f]=Y(b[f]),c[f]=Y(c[f]);for(f=0;24>f;f++)d[f]=Y(d[f]);this._monthsShortRegex=this._monthsRegex=new RegExp("^("+d.join("|")+")","i");this._monthsStrictRegex=new RegExp("^("+c.join("|")+")","i");this._monthsShortStrictRegex=new RegExp("^("+b.join("|")+")","i")}function ga(a){return 0===a%4&&0!==a%100||0===a%400}function bc(a,b,c,d,f,e,g){b=new Date(a,b,c,d,f,e,g);100>a&&0<=a&&isFinite(b.getFullYear())&&b.setFullYear(a);
return b}function ua(a){var b=new Date(Date.UTC.apply(null,arguments));100>a&&0<=a&&isFinite(b.getUTCFullYear())&&b.setUTCFullYear(a);return b}function va(a,b,c){c=7+b-c;return-((7+ua(a,0,c).getUTCDay()-b)%7)+c-1}function tb(a,b,c,d,f){c=(7+c-d)%7;d=va(a,d,f);d=1+7*(b-1)+c+d;0>=d?(b=a-1,a=(ga(b)?366:365)+d):d>(ga(a)?366:365)?(b=a+1,a=d-(ga(a)?366:365)):(b=a,a=d);return{year:b,dayOfYear:a}}function ma(a,b,c){var d=va(a.year(),b,c),d=Math.floor((a.dayOfYear()-d-1)/7)+1;1>d?(a=a.year()-1,b=d+Z(a,b,c)):
d>Z(a.year(),b,c)?(b=d-Z(a.year(),b,c),a=a.year()+1):(a=a.year(),b=d);return{week:b,year:a}}function Z(a,b,c){var d=va(a,b,c);b=va(a+1,b,c);return((ga(a)?366:365)-d+b)/7}function cc(a,b,c){var d,f;a=a.toLocaleLowerCase();if(!this._weekdaysParse)for(this._weekdaysParse=[],this._shortWeekdaysParse=[],this._minWeekdaysParse=[],d=0;7>d;++d)f=I([2E3,1]).day(d),this._minWeekdaysParse[d]=this.weekdaysMin(f,"").toLocaleLowerCase(),this._shortWeekdaysParse[d]=this.weekdaysShort(f,"").toLocaleLowerCase(),this._weekdaysParse[d]=
this.weekdays(f,"").toLocaleLowerCase();if(c)b="dddd"===b?w.call(this._weekdaysParse,a):"ddd"===b?w.call(this._shortWeekdaysParse,a):w.call(this._minWeekdaysParse,a);else if("dddd"===b){b=w.call(this._weekdaysParse,a);if(-1!==b)return b;b=w.call(this._shortWeekdaysParse,a);if(-1!==b)return b;b=w.call(this._minWeekdaysParse,a)}else if("ddd"===b){b=w.call(this._shortWeekdaysParse,a);if(-1!==b)return b;b=w.call(this._weekdaysParse,a);if(-1!==b)return b;b=w.call(this._minWeekdaysParse,a)}else{b=w.call(this._minWeekdaysParse,
a);if(-1!==b)return b;b=w.call(this._weekdaysParse,a);if(-1!==b)return b;b=w.call(this._shortWeekdaysParse,a)}return-1!==b?b:null}function Sa(){function a(a,b){return b.length-a.length}var b=[],c=[],d=[],f=[],e,g,h,k;for(e=0;7>e;e++)g=I([2E3,1]).day(e),h=this.weekdaysMin(g,""),k=this.weekdaysShort(g,""),g=this.weekdays(g,""),b.push(h),c.push(k),d.push(g),f.push(h),f.push(k),f.push(g);b.sort(a);c.sort(a);d.sort(a);f.sort(a);for(e=0;7>e;e++)c[e]=Y(c[e]),d[e]=Y(d[e]),f[e]=Y(f[e]);this._weekdaysMinRegex=
this._weekdaysShortRegex=this._weekdaysRegex=new RegExp("^("+f.join("|")+")","i");this._weekdaysStrictRegex=new RegExp("^("+d.join("|")+")","i");this._weekdaysShortStrictRegex=new RegExp("^("+c.join("|")+")","i");this._weekdaysMinStrictRegex=new RegExp("^("+b.join("|")+")","i")}function Ta(){return this.hours()%12||12}function ub(a,b){k(a,0,0,function(){return this.localeData().meridiem(this.hours(),this.minutes(),b)})}function vb(a,b){return b._meridiemParse}function wb(a){return a?a.toLowerCase().replace("_",
"-"):a}function xb(a){var b=null;if(!v[a]&&"undefined"!==typeof module&&module&&module.exports)try{b=wa._abbr,require("./locale/"+a),ha(b)}catch(c){}return v[a]}function ha(a,b){var c;a&&(c=A(b)?S(a):Ua(a,b))&&(wa=c);return wa._abbr}function Ua(a,b){if(null!==b){var c=yb;b.abbr=a;if(null!=v[a])lb("defineLocaleOverride","use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info."),
c=v[a]._config;else if(null!=b.parentLocale)if(null!=v[b.parentLocale])c=v[b.parentLocale]._config;else return na[b.parentLocale]||(na[b.parentLocale]=[]),na[b.parentLocale].push({name:a,config:b}),null;v[a]=new La(nb(c,b));na[a]&&na[a].forEach(function(a){Ua(a.name,a.config)});ha(a);return v[a]}delete v[a];return null}function S(a){var b;a&&a._locale&&a._locale._abbr&&(a=a._locale._abbr);if(!a)return wa;if(!H(a)){if(b=xb(a))return b;a=[a]}a:{b=0;for(var c,d,f,e;b<a.length;){e=wb(a[b]).split("-");
c=e.length;for(d=(d=wb(a[b+1]))?d.split("-"):null;0<c;){if(f=xb(e.slice(0,c).join("-"))){a=f;break a}if(d&&d.length>=c&&jb(e,d,!0)>=c-1)break;c--}b++}a=null}return a}function Va(a){var b;(b=a._a)&&-2===n(a).overflow&&(b=0>b[M]||11<b[M]?M:1>b[J]||b[J]>Ra(b[F],b[M])?J:0>b[x]||24<b[x]||24===b[x]&&(0!==b[G]||0!==b[N]||0!==b[aa])?x:0>b[G]||59<b[G]?G:0>b[N]||59<b[N]?N:0>b[aa]||999<b[aa]?aa:-1,n(a)._overflowDayOfYear&&(b<F||b>J)&&(b=J),n(a)._overflowWeeks&&-1===b&&(b=dc),n(a)._overflowWeekday&&-1===b&&(b=
ec),n(a).overflow=b);return a}function zb(a){var b,c;b=a._i;var d=fc.exec(b)||gc.exec(b),f,e,g,h;if(d){n(a).iso=!0;b=0;for(c=xa.length;b<c;b++)if(xa[b][1].exec(d[1])){e=xa[b][0];f=!1!==xa[b][2];break}if(null==e)a._isValid=!1;else{if(d[3]){b=0;for(c=Wa.length;b<c;b++)if(Wa[b][1].exec(d[3])){g=(d[2]||" ")+Wa[b][0];break}if(null==g){a._isValid=!1;return}}if(f||null==g){if(d[4])if(hc.exec(d[4]))h="Z";else{a._isValid=!1;return}a._f=e+(g||"")+(h||"");Xa(a)}else a._isValid=!1}}else a._isValid=!1}function ic(a){var b=
jc.exec(a._i);null!==b?a._d=new Date(+b[1]):(zb(a),!1===a._isValid&&(delete a._isValid,g.createFromInputFallback(a)))}function ia(a,b,c){return null!=a?a:null!=b?b:c}function Ya(a){var b,c=[],d;if(!a._d){d=new Date(g.now());d=a._useUTC?[d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()]:[d.getFullYear(),d.getMonth(),d.getDate()];if(a._w&&null==a._a[J]&&null==a._a[M]){var f,e,h,k,l,m;f=a._w;if(null!=f.GG||null!=f.W||null!=f.E){if(l=1,m=4,e=ia(f.GG,a._a[F],ma(r(),1,4).year),h=ia(f.W,1),k=ia(f.E,1),
1>k||7<k)b=!0}else if(l=a._locale._week.dow,m=a._locale._week.doy,h=ma(r(),l,m),e=ia(f.gg,a._a[F],h.year),h=ia(f.w,h.week),null!=f.d){if(k=f.d,0>k||6<k)b=!0}else if(null!=f.e){if(k=f.e+l,0>f.e||6<f.e)b=!0}else k=l;1>h||h>Z(e,l,m)?n(a)._overflowWeeks=!0:null!=b?n(a)._overflowWeekday=!0:(b=tb(e,h,k,l,m),a._a[F]=b.year,a._dayOfYear=b.dayOfYear)}a._dayOfYear&&(b=ia(a._a[F],d[F]),a._dayOfYear>(ga(b)?366:365)&&(n(a)._overflowDayOfYear=!0),b=ua(b,0,a._dayOfYear),a._a[M]=b.getUTCMonth(),a._a[J]=b.getUTCDate());
for(b=0;3>b&&null==a._a[b];++b)a._a[b]=c[b]=d[b];for(;7>b;b++)a._a[b]=c[b]=null==a._a[b]?2===b?1:0:a._a[b];24===a._a[x]&&0===a._a[G]&&0===a._a[N]&&0===a._a[aa]&&(a._nextDay=!0,a._a[x]=0);a._d=(a._useUTC?ua:bc).apply(null,c);null!=a._tzm&&a._d.setUTCMinutes(a._d.getUTCMinutes()-a._tzm);a._nextDay&&(a._a[x]=24)}}function Xa(a){if(a._f===g.ISO_8601)zb(a);else{a._a=[];n(a).empty=!0;var b=""+a._i,c,d,f,e,h,k=b.length,l=0;f=pb(a._f,a._locale).match(ob)||[];for(c=0;c<f.length;c++){e=f[c];if(d=(b.match($b(e,
a))||[])[0])h=b.substr(0,b.indexOf(d)),0<h.length&&n(a).unusedInput.push(h),b=b.slice(b.indexOf(d)+d.length),l+=d.length;if(fa[e]){if(d?n(a).empty=!1:n(a).unusedTokens.push(e),h=a,null!=d&&u(Qa,e))Qa[e](d,h._a,h,e)}else a._strict&&!d&&n(a).unusedTokens.push(e)}n(a).charsLeftOver=k-l;0<b.length&&n(a).unusedInput.push(b);12>=a._a[x]&&!0===n(a).bigHour&&0<a._a[x]&&(n(a).bigHour=void 0);n(a).parsedDateParts=a._a.slice(0);n(a).meridiem=a._meridiem;b=a._a;c=x;k=a._locale;f=a._a[x];l=a._meridiem;null!=l&&
(null!=k.meridiemHour?f=k.meridiemHour(f,l):null!=k.isPM&&((k=k.isPM(l))&&12>f&&(f+=12),k||12!==f||(f=0)));b[c]=f;Ya(a);Va(a)}}function kc(a){if(!a._d){var b=Ma(a._i);a._a=hb([b.year,b.month,b.day||b.date,b.hour,b.minute,b.second,b.millisecond],function(a){return a&&parseInt(a,10)});Ya(a)}}function Ab(a){var b=a._i,c=a._f;a._locale=a._locale||S(a._l);if(null===b||void 0===c&&""===b)return ra({nullInput:!0});"string"===typeof b&&(a._i=b=a._locale.preparse(b));if(Q(b))return new ja(Va(b));if(qa(b))a._d=
b;else if(H(c)){var d,f,e;if(0===a._f.length)n(a).invalidFormat=!0,a._d=new Date(NaN);else{for(b=0;b<a._f.length;b++)if(c=0,d=Ia({},a),null!=a._useUTC&&(d._useUTC=a._useUTC),d._f=a._f[b],Xa(d),Ha(d)&&(c+=n(d).charsLeftOver,c+=10*n(d).unusedTokens.length,n(d).score=c,null==e||c<e))e=c,f=d;P(a,f||d)}}else c?Xa(a):lc(a);Ha(a)||(a._d=null);return a}function lc(a){var b=a._i;void 0===b?a._d=new Date(g.now()):qa(b)?a._d=new Date(b.valueOf()):"string"===typeof b?ic(a):H(b)?(a._a=hb(b.slice(0),function(a){return parseInt(a,
10)}),Ya(a)):"object"===typeof b?kc(a):da(b)?a._d=new Date(b):g.createFromInputFallback(a)}function ib(a,b,c,d,f){var e={};if(!0===c||!1===c)d=c,c=void 0;var g;if(g=pa(a))a:{g=a;for(var h in g){g=!1;break a}g=!0}if(g||H(a)&&0===a.length)a=void 0;e._isAMomentObject=!0;e._useUTC=e._isUTC=f;e._l=c;e._i=a;e._f=b;e._strict=d;a=new ja(Va(Ab(e)));a._nextDay&&(a.add(1,"d"),a._nextDay=void 0);return a}function r(a,b,c,d){return ib(a,b,c,d,!1)}function Bb(a,b){var c,d;1===b.length&&H(b[0])&&(b=b[0]);if(!b.length)return r();
c=b[0];for(d=1;d<b.length;++d)if(!b[d].isValid()||b[d][a](c))c=b[d];return c}function ya(a){a=Ma(a);var b=a.year||0,c=a.quarter||0,d=a.month||0,f=a.week||0,e=a.day||0;this._milliseconds=+(a.millisecond||0)+1E3*(a.second||0)+6E4*(a.minute||0)+36E5*(a.hour||0);this._days=+e+7*f;this._months=+d+3*c+12*b;this._data={};this._locale=S();this._bubble()}function Za(a){return a instanceof ya}function $a(a){return 0>a?-1*Math.round(-1*a):Math.round(a)}function Cb(a,b){k(a,0,0,function(){var a=this.utcOffset(),
d="+";0>a&&(a=-a,d="-");return d+L(~~(a/60),2)+b+L(~~a%60,2)})}function ab(a,b){var c=(b||"").match(a);if(null===c)return null;var c=((c[c.length-1]||[])+"").match(mc)||["-",0,0],d=+(60*c[1])+l(c[2]);return 0===d?0:"+"===c[0]?d:-d}function bb(a,b){var c,d;return b._isUTC?(c=b.clone(),d=(Q(a)||qa(a)?a.valueOf():r(a).valueOf())-c.valueOf(),c._d.setTime(c._d.valueOf()+d),g.updateOffset(c,!1),c):r(a).local()}function Db(){return this.isValid()?this._isUTC&&0===this._offset:!1}function T(a,b){var c=a,
d;Za(a)?c={ms:a._milliseconds,d:a._days,M:a._months}:da(a)?(c={},b?c[b]=a:c.milliseconds=a):(d=nc.exec(a))?(c="-"===d[1]?-1:1,c={y:0,d:l(d[J])*c,h:l(d[x])*c,m:l(d[G])*c,s:l(d[N])*c,ms:l($a(1E3*d[aa]))*c}):(d=oc.exec(a))?(c="-"===d[1]?-1:1,c={y:ba(d[2],c),M:ba(d[3],c),w:ba(d[4],c),d:ba(d[5],c),h:ba(d[6],c),m:ba(d[7],c),s:ba(d[8],c)}):null==c?c={}:"object"===typeof c&&("from"in c||"to"in c)&&(d=r(c.from),c=r(c.to),d.isValid()&&c.isValid()?(c=bb(c,d),d.isBefore(c)?c=Eb(d,c):(c=Eb(c,d),c.milliseconds=
-c.milliseconds,c.months=-c.months),d=c):d={milliseconds:0,months:0},c={},c.ms=d.milliseconds,c.M=d.months);c=new ya(c);Za(a)&&u(a,"_locale")&&(c._locale=a._locale);return c}function ba(a,b){var c=a&&parseFloat(a.replace(",","."));return(isNaN(c)?0:c)*b}function Eb(a,b){var c={milliseconds:0,months:0};c.months=b.month()-a.month()+12*(b.year()-a.year());a.clone().add(c.months,"M").isAfter(b)&&--c.months;c.milliseconds=+b-+a.clone().add(c.months,"M");return c}function Fb(a,b){return function(c,d){var f;
null===d||isNaN(+d)||(lb(b,"moment()."+b+"(period, number) is deprecated. Please use moment()."+b+"(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info."),f=c,c=d,d=f);f=T("string"===typeof c?+c:c,d);Gb(this,f,a);return this}}function Gb(a,b,c,d){var f=b._milliseconds,e=$a(b._days);b=$a(b._months);if(a.isValid()){d=null==d?!0:d;f&&a._d.setTime(a._d.valueOf()+f*c);if(e&&(f=sa(a,"Date")+e*c,a.isValid()))a._d["set"+(a._isUTC?"UTC":"")+"Date"](f);b&&qb(a,sa(a,
"Month")+b*c);d&&g.updateOffset(a,e||b)}}function Hb(a){if(void 0===a)return this._locale._abbr;a=S(a);null!=a&&(this._locale=a);return this}function Ib(){return this._locale}function za(a,b){k(0,[a,a.length],0,b)}function Jb(a,b,c,d,f){var e;if(null==a)return ma(this,d,f).year;e=Z(a,d,f);b>e&&(b=e);a=tb(a,b,c,d,f);a=ua(a.year,0,a.dayOfYear);this.year(a.getUTCFullYear());this.month(a.getUTCMonth());this.date(a.getUTCDate());return this}function pc(a,b){b[aa]=l(1E3*("0."+a))}function Kb(a){return a}
function Aa(a,b,c,d){var e=S();b=I().set(d,b);return e[c](b,a)}function Lb(a,b,c){da(a)&&(b=a,a=void 0);a=a||"";if(null!=b)return Aa(a,b,c,"month");var d=[];for(b=0;12>b;b++)d[b]=Aa(a,b,c,"month");return d}function cb(a,b,c,d){"boolean"!==typeof a&&(c=b=a,a=!1);da(b)&&(c=b,b=void 0);b=b||"";var e=S();a=a?e._week.dow:0;if(null!=c)return Aa(b,(c+a)%7,d,"day");e=[];for(c=0;7>c;c++)e[c]=Aa(b,(c+a)%7,d,"day");return e}function Mb(a,b,c,d){b=T(b,c);a._milliseconds+=d*b._milliseconds;a._days+=d*b._days;
a._months+=d*b._months;return a._bubble()}function Nb(a){return 0>a?Math.floor(a):Math.ceil(a)}function U(a){return function(){return this.as(a)}}function ca(a){return function(){return this._data[a]}}function qc(a,b,c,d,e){return e.relativeTime(b||1,!!c,a,d)}function Ba(){var a=db(this._milliseconds)/1E3,b=db(this._days),c=db(this._months),d,e;d=B(a/60);e=B(d/60);a%=60;d%=60;var g=B(c/12),c=c%12,h=this.asSeconds();return h?(0>h?"-":"")+"P"+(g?g+"Y":"")+(c?c+"M":"")+(b?b+"D":"")+(e||d||a?"T":"")+
(e?e+"H":"")+(d?d+"M":"")+(a?a+"S":""):"P0D"}var gb,Wb=Array.prototype.some?Array.prototype.some:function(a){for(var b=Object(this),c=b.length>>>0,d=0;d<c;d++)if(d in b&&a.call(this,b[d],d,b))return!0;return!1},Ja=g.momentProperties=[],Ka=!1,mb={};g.suppressDeprecationWarnings=!1;g.deprecationHandler=null;var rc=Object.keys?Object.keys:function(a){var b,c=[];for(b in a)u(a,b)&&c.push(b);return c},ka={},y={},ob=/(\[[^\[]*\])|(\\)?([Hh]mm(ss)?|Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|Qo?|YYYYYY|YYYYY|YYYY|YY|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|kk?|mm?|ss?|S{1,9}|x|X|zz?|ZZ?|.)/g,
ta=/(\[[^\[]*\])|(\\)?(LTS|LT|LL?L?L?|l{1,4})/g,Oa={},fa={},Ob=/\d/,E=/\d\d/,Pb=/\d{3}/,eb=/\d{4}/,Ca=/[+-]?\d{6}/,t=/\d\d?/,Qb=/\d\d\d\d?/,Rb=/\d\d\d\d\d\d?/,Da=/\d{1,3}/,fb=/\d{1,4}/,Ea=/[+-]?\d{1,6}/,sc=/\d+/,Fa=/[+-]?\d+/,tc=/Z|[+-]\d\d:?\d\d/gi,Ga=/Z|[+-]\d\d(?::?\d\d)?/gi,oa=/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i,Pa={},Qa={},F=0,M=1,J=2,x=3,G=4,N=5,aa=6,dc=7,ec=8,w=Array.prototype.indexOf?Array.prototype.indexOf:function(a){var b;
for(b=0;b<this.length;++b)if(this[b]===a)return b;return-1};k("M",["MM",2],"Mo",function(){return this.month()+1});k("MMM",0,0,function(a){return this.localeData().monthsShort(this,a)});k("MMMM",0,0,function(a){return this.localeData().months(this,a)});z("month","M");y.month=8;h("M",t);h("MM",t,E);h("MMM",function(a,b){return b.monthsShortRegex(a)});h("MMMM",function(a,b){return b.monthsRegex(a)});q(["M","MM"],function(a,b){b[M]=l(a)-1});q(["MMM","MMMM"],function(a,b,c,d){d=c._locale.monthsParse(a,
d,c._strict);null!=d?b[M]=d:n(c).invalidMonth=a});var Sb=/D[oD]?(\[[^\[\]]*\]|\s)+MMMM?/;k("Y",0,0,function(){var a=this.year();return 9999>=a?""+a:"+"+a});k(0,["YY",2],0,function(){return this.year()%100});k(0,["YYYY",4],0,"year");k(0,["YYYYY",5],0,"year");k(0,["YYYYYY",6,!0],0,"year");z("year","y");y.year=1;h("Y",Fa);h("YY",t,E);h("YYYY",fb,eb);h("YYYYY",Ea,Ca);h("YYYYYY",Ea,Ca);q(["YYYYY","YYYYYY"],F);q("YYYY",function(a,b){b[F]=2===a.length?g.parseTwoDigitYear(a):l(a)});q("YY",function(a,b){b[F]=
g.parseTwoDigitYear(a)});q("Y",function(a,b){b[F]=parseInt(a,10)});g.parseTwoDigitYear=function(a){return l(a)+(68<l(a)?1900:2E3)};var Tb=ea("FullYear",!0);k("w",["ww",2],"wo","week");k("W",["WW",2],"Wo","isoWeek");z("week","w");z("isoWeek","W");y.week=5;y.isoWeek=5;h("w",t);h("ww",t,E);h("W",t);h("WW",t,E);la(["w","ww","W","WW"],function(a,b,c,d){b[d.substr(0,1)]=l(a)});k("d",0,"do","day");k("dd",0,0,function(a){return this.localeData().weekdaysMin(this,a)});k("ddd",0,0,function(a){return this.localeData().weekdaysShort(this,
a)});k("dddd",0,0,function(a){return this.localeData().weekdays(this,a)});k("e",0,0,"weekday");k("E",0,0,"isoWeekday");z("day","d");z("weekday","e");z("isoWeekday","E");y.day=11;y.weekday=11;y.isoWeekday=11;h("d",t);h("e",t);h("E",t);h("dd",function(a,b){return b.weekdaysMinRegex(a)});h("ddd",function(a,b){return b.weekdaysShortRegex(a)});h("dddd",function(a,b){return b.weekdaysRegex(a)});la(["dd","ddd","dddd"],function(a,b,c,d){d=c._locale.weekdaysParse(a,d,c._strict);null!=d?b.d=d:n(c).invalidWeekday=
a});la(["d","e","E"],function(a,b,c,d){b[d]=l(a)});k("H",["HH",2],0,"hour");k("h",["hh",2],0,Ta);k("k",["kk",2],0,function(){return this.hours()||24});k("hmm",0,0,function(){return""+Ta.apply(this)+L(this.minutes(),2)});k("hmmss",0,0,function(){return""+Ta.apply(this)+L(this.minutes(),2)+L(this.seconds(),2)});k("Hmm",0,0,function(){return""+this.hours()+L(this.minutes(),2)});k("Hmmss",0,0,function(){return""+this.hours()+L(this.minutes(),2)+L(this.seconds(),2)});ub("a",!0);ub("A",!1);z("hour","h");
y.hour=13;h("a",vb);h("A",vb);h("H",t);h("h",t);h("HH",t,E);h("hh",t,E);h("hmm",Qb);h("hmmss",Rb);h("Hmm",Qb);h("Hmmss",Rb);q(["H","HH"],x);q(["a","A"],function(a,b,c){c._isPm=c._locale.isPM(a);c._meridiem=a});q(["h","hh"],function(a,b,c){b[x]=l(a);n(c).bigHour=!0});q("hmm",function(a,b,c){var d=a.length-2;b[x]=l(a.substr(0,d));b[G]=l(a.substr(d));n(c).bigHour=!0});q("hmmss",function(a,b,c){var d=a.length-4,e=a.length-2;b[x]=l(a.substr(0,d));b[G]=l(a.substr(d,2));b[N]=l(a.substr(e));n(c).bigHour=
!0});q("Hmm",function(a,b,c){c=a.length-2;b[x]=l(a.substr(0,c));b[G]=l(a.substr(c))});q("Hmmss",function(a,b,c){c=a.length-4;var d=a.length-2;b[x]=l(a.substr(0,c));b[G]=l(a.substr(c,2));b[N]=l(a.substr(d))});var uc=ea("Hours",!0),yb={calendar:{sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[Last] dddd [at] LT",sameElse:"L"},longDateFormat:{LTS:"h:mm:ss A",LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D, YYYY",LLL:"MMMM D, YYYY h:mm A",LLLL:"dddd, MMMM D, YYYY h:mm A"},
invalidDate:"Invalid date",ordinal:"%d",ordinalParse:/\d{1,2}/,relativeTime:{future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"},months:"January February March April May June July August September October November December".split(" "),monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),week:{dow:0,doy:6},weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
weekdaysMin:"Su Mo Tu We Th Fr Sa".split(" "),weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),meridiemParse:/[ap]\.?m?\.?/i},v={},na={},wa,fc=/^\s*((?:[+-]\d{6}|\d{4})-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/,gc=/^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/,hc=/Z|[+-]\d\d(?::?\d\d)?/,xa=[["YYYYYY-MM-DD",/[+-]\d{6}-\d\d-\d\d/],
["YYYY-MM-DD",/\d{4}-\d\d-\d\d/],["GGGG-[W]WW-E",/\d{4}-W\d\d-\d/],["GGGG-[W]WW",/\d{4}-W\d\d/,!1],["YYYY-DDD",/\d{4}-\d{3}/],["YYYY-MM",/\d{4}-\d\d/,!1],["YYYYYYMMDD",/[+-]\d{10}/],["YYYYMMDD",/\d{8}/],["GGGG[W]WWE",/\d{4}W\d{3}/],["GGGG[W]WW",/\d{4}W\d{2}/,!1],["YYYYDDD",/\d{7}/]],Wa=[["HH:mm:ss.SSSS",/\d\d:\d\d:\d\d\.\d+/],["HH:mm:ss,SSSS",/\d\d:\d\d:\d\d,\d+/],["HH:mm:ss",/\d\d:\d\d:\d\d/],["HH:mm",/\d\d:\d\d/],["HHmmss.SSSS",/\d\d\d\d\d\d\.\d+/],["HHmmss,SSSS",/\d\d\d\d\d\d,\d+/],["HHmmss",/\d\d\d\d\d\d/],
["HHmm",/\d\d\d\d/],["HH",/\d\d/]],jc=/^\/?Date\((\-?\d+)/i;g.createFromInputFallback=C("value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.",function(a){a._d=new Date(a._i+(a._useUTC?" UTC":""))});g.ISO_8601=function(){};var vc=C("moment().min is deprecated, use moment.max instead. http://momentjs.com/guides/#/warnings/min-max/",
function(){var a=r.apply(null,arguments);return this.isValid()&&a.isValid()?a<this?this:a:ra()}),wc=C("moment().max is deprecated, use moment.min instead. http://momentjs.com/guides/#/warnings/min-max/",function(){var a=r.apply(null,arguments);return this.isValid()&&a.isValid()?a>this?this:a:ra()});Cb("Z",":");Cb("ZZ","");h("Z",Ga);h("ZZ",Ga);q(["Z","ZZ"],function(a,b,c){c._useUTC=!0;c._tzm=ab(Ga,a)});var mc=/([\+\-]|\d\d)/gi;g.updateOffset=function(){};var nc=/^(\-)?(?:(\d*)[. ])?(\d+)\:(\d+)(?:\:(\d+)(\.\d*)?)?$/,
oc=/^(-)?P(?:(-?[0-9,.]*)Y)?(?:(-?[0-9,.]*)M)?(?:(-?[0-9,.]*)W)?(?:(-?[0-9,.]*)D)?(?:T(?:(-?[0-9,.]*)H)?(?:(-?[0-9,.]*)M)?(?:(-?[0-9,.]*)S)?)?$/;T.fn=ya.prototype;var xc=Fb(1,"add"),yc=Fb(-1,"subtract");g.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";g.defaultFormatUtc="YYYY-MM-DDTHH:mm:ss[Z]";var Ub=C("moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.",function(a){return void 0===a?this.localeData():this.locale(a)});
k(0,["gg",2],0,function(){return this.weekYear()%100});k(0,["GG",2],0,function(){return this.isoWeekYear()%100});za("gggg","weekYear");za("ggggg","weekYear");za("GGGG","isoWeekYear");za("GGGGG","isoWeekYear");z("weekYear","gg");z("isoWeekYear","GG");y.weekYear=1;y.isoWeekYear=1;h("G",Fa);h("g",Fa);h("GG",t,E);h("gg",t,E);h("GGGG",fb,eb);h("gggg",fb,eb);h("GGGGG",Ea,Ca);h("ggggg",Ea,Ca);la(["gggg","ggggg","GGGG","GGGGG"],function(a,b,c,d){b[d.substr(0,2)]=l(a)});la(["gg","GG"],function(a,b,c,d){b[d]=
g.parseTwoDigitYear(a)});k("Q",0,"Qo","quarter");z("quarter","Q");y.quarter=7;h("Q",Ob);q("Q",function(a,b){b[M]=3*(l(a)-1)});k("D",["DD",2],"Do","date");z("date","D");y.date=9;h("D",t);h("DD",t,E);h("Do",function(a,b){return a?b._ordinalParse:b._ordinalParseLenient});q(["D","DD"],J);q("Do",function(a,b){b[J]=l(a.match(t)[0],10)});var Vb=ea("Date",!0);k("DDD",["DDDD",3],"DDDo","dayOfYear");z("dayOfYear","DDD");y.dayOfYear=4;h("DDD",Da);h("DDDD",Pb);q(["DDD","DDDD"],function(a,b,c){c._dayOfYear=l(a)});
k("m",["mm",2],0,"minute");z("minute","m");y.minute=14;h("m",t);h("mm",t,E);q(["m","mm"],G);var zc=ea("Minutes",!1);k("s",["ss",2],0,"second");z("second","s");y.second=15;h("s",t);h("ss",t,E);q(["s","ss"],N);var Ac=ea("Seconds",!1);k("S",0,0,function(){return~~(this.millisecond()/100)});k(0,["SS",2],0,function(){return~~(this.millisecond()/10)});k(0,["SSS",3],0,"millisecond");k(0,["SSSS",4],0,function(){return 10*this.millisecond()});k(0,["SSSSS",5],0,function(){return 100*this.millisecond()});k(0,
["SSSSSS",6],0,function(){return 1E3*this.millisecond()});k(0,["SSSSSSS",7],0,function(){return 1E4*this.millisecond()});k(0,["SSSSSSSS",8],0,function(){return 1E5*this.millisecond()});k(0,["SSSSSSSSS",9],0,function(){return 1E6*this.millisecond()});z("millisecond","ms");y.millisecond=16;h("S",Da,Ob);h("SS",Da,E);h("SSS",Da,Pb);var V;for(V="SSSS";9>=V.length;V+="S")h(V,sc);for(V="S";9>=V.length;V+="S")q(V,pc);var Bc=ea("Milliseconds",!1);k("z",0,0,"zoneAbbr");k("zz",0,0,"zoneName");var e=ja.prototype;
e.add=xc;e.calendar=function(a,b){var c=a||r(),d=bb(c,this).startOf("day"),d=g.calendarFormat(this,d)||"sameElse",e=b&&(K(b[d])?b[d].call(this,c):b[d]);return this.format(e||this.localeData().calendar(d,this,r(c)))};e.clone=function(){return new ja(this)};e.diff=function(a,b,c){var d;if(!this.isValid())return NaN;a=bb(a,this);if(!a.isValid())return NaN;d=6E4*(a.utcOffset()-this.utcOffset());b=D(b);if("year"===b||"month"===b||"quarter"===b){d=12*(a.year()-this.year())+(a.month()-this.month());var e=
this.clone().add(d,"months"),g;0>a-e?(g=this.clone().add(d-1,"months"),a=(a-e)/(e-g)):(g=this.clone().add(d+1,"months"),a=(a-e)/(g-e));a=-(d+a)||0;"quarter"===b?a/=3:"year"===b&&(a/=12)}else a=this-a,a="second"===b?a/1E3:"minute"===b?a/6E4:"hour"===b?a/36E5:"day"===b?(a-d)/864E5:"week"===b?(a-d)/6048E5:a;return c?a:B(a)};e.endOf=function(a){a=D(a);if(void 0===a||"millisecond"===a)return this;"date"===a&&(a="day");return this.startOf(a).add(1,"isoWeek"===a?"week":a).subtract(1,"ms")};e.format=function(a){a||
(a=this.isUtc()?g.defaultFormatUtc:g.defaultFormat);a=Na(this,a);return this.localeData().postformat(a)};e.from=function(a,b){return this.isValid()&&(Q(a)&&a.isValid()||r(a).isValid())?T({to:this,from:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};e.fromNow=function(a){return this.from(r(),a)};e.to=function(a,b){return this.isValid()&&(Q(a)&&a.isValid()||r(a).isValid())?T({from:this,to:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};e.toNow=function(a){return this.to(r(),
a)};e.get=function(a){a=D(a);return K(this[a])?this[a]():this};e.invalidAt=function(){return n(this).overflow};e.isAfter=function(a,b){var c=Q(a)?a:r(a);if(!this.isValid()||!c.isValid())return!1;b=D(A(b)?"millisecond":b);return"millisecond"===b?this.valueOf()>c.valueOf():c.valueOf()<this.clone().startOf(b).valueOf()};e.isBefore=function(a,b){var c=Q(a)?a:r(a);if(!this.isValid()||!c.isValid())return!1;b=D(A(b)?"millisecond":b);return"millisecond"===b?this.valueOf()<c.valueOf():this.clone().endOf(b).valueOf()<
c.valueOf()};e.isBetween=function(a,b,c,d){d=d||"()";return("("===d[0]?this.isAfter(a,c):!this.isBefore(a,c))&&(")"===d[1]?this.isBefore(b,c):!this.isAfter(b,c))};e.isSame=function(a,b){var c=Q(a)?a:r(a);if(!this.isValid()||!c.isValid())return!1;b=D(b||"millisecond");if("millisecond"===b)return this.valueOf()===c.valueOf();c=c.valueOf();return this.clone().startOf(b).valueOf()<=c&&c<=this.clone().endOf(b).valueOf()};e.isSameOrAfter=function(a,b){return this.isSame(a,b)||this.isAfter(a,b)};e.isSameOrBefore=
function(a,b){return this.isSame(a,b)||this.isBefore(a,b)};e.isValid=function(){return Ha(this)};e.lang=Ub;e.locale=Hb;e.localeData=Ib;e.max=wc;e.min=vc;e.parsingFlags=function(){return P({},n(this))};e.set=function(a,b){if("object"===typeof a){a=Ma(a);for(var c=Xb(a),d=0;d<c.length;d++)this[c[d].unit](a[c[d].unit])}else if(a=D(a),K(this[a]))return this[a](b);return this};e.startOf=function(a){a=D(a);switch(a){case "year":this.month(0);case "quarter":case "month":this.date(1);case "week":case "isoWeek":case "day":case "date":this.hours(0);
case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}"week"===a&&this.weekday(0);"isoWeek"===a&&this.isoWeekday(1);"quarter"===a&&this.month(3*Math.floor(this.month()/3));return this};e.subtract=yc;e.toArray=function(){return[this.year(),this.month(),this.date(),this.hour(),this.minute(),this.second(),this.millisecond()]};e.toObject=function(){return{years:this.year(),months:this.month(),date:this.date(),hours:this.hours(),minutes:this.minutes(),seconds:this.seconds(),
milliseconds:this.milliseconds()}};e.toDate=function(){return new Date(this.valueOf())};e.toISOString=function(){var a=this.clone().utc();return 0<a.year()&&9999>=a.year()?K(Date.prototype.toISOString)?this.toDate().toISOString():Na(a,"YYYY-MM-DD[T]HH:mm:ss.SSS[Z]"):Na(a,"YYYYYY-MM-DD[T]HH:mm:ss.SSS[Z]")};e.inspect=function(){if(!this.isValid())return"moment.invalid(/* "+this._i+" */)";var a="moment",b="";this.isLocal()||(a=0===this.utcOffset()?"moment.utc":"moment.parseZone",b="Z");var a="["+a+'("]',
c=0<this.year()&&9999>=this.year()?"YYYY":"YYYYYY";return this.format(a+c+"-MM-DD[T]HH:mm:ss.SSS"+(b+'[")]'))};e.toJSON=function(){return this.isValid()?this.toISOString():null};e.toString=function(){return this.clone().locale("en").format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")};e.unix=function(){return Math.floor(this.valueOf()/1E3)};e.valueOf=function(){return this._d.valueOf()-6E4*(this._offset||0)};e.creationData=function(){return{input:this._i,format:this._f,locale:this._locale,isUTC:this._isUTC,
strict:this._strict}};e.year=Tb;e.isLeapYear=function(){return ga(this.year())};e.weekYear=function(a){return Jb.call(this,a,this.week(),this.weekday(),this.localeData()._week.dow,this.localeData()._week.doy)};e.isoWeekYear=function(a){return Jb.call(this,a,this.isoWeek(),this.isoWeekday(),1,4)};e.quarter=e.quarters=function(a){return null==a?Math.ceil((this.month()+1)/3):this.month(3*(a-1)+this.month()%3)};e.month=rb;e.daysInMonth=function(){return Ra(this.year(),this.month())};e.week=e.weeks=function(a){var b=
this.localeData().week(this);return null==a?b:this.add(7*(a-b),"d")};e.isoWeek=e.isoWeeks=function(a){var b=ma(this,1,4).week;return null==a?b:this.add(7*(a-b),"d")};e.weeksInYear=function(){var a=this.localeData()._week;return Z(this.year(),a.dow,a.doy)};e.isoWeeksInYear=function(){return Z(this.year(),1,4)};e.date=Vb;e.day=e.days=function(a){if(!this.isValid())return null!=a?this:NaN;var b=this._isUTC?this._d.getUTCDay():this._d.getDay();if(null!=a){var c=this.localeData();"string"===typeof a&&
(isNaN(a)?(a=c.weekdaysParse(a),a="number"===typeof a?a:null):a=parseInt(a,10));return this.add(a-b,"d")}return b};e.weekday=function(a){if(!this.isValid())return null!=a?this:NaN;var b=(this.day()+7-this.localeData()._week.dow)%7;return null==a?b:this.add(a-b,"d")};e.isoWeekday=function(a){if(!this.isValid())return null!=a?this:NaN;if(null!=a){var b=this.localeData();a="string"===typeof a?b.weekdaysParse(a)%7||7:isNaN(a)?null:a;return this.day(this.day()%7?a:a-7)}return this.day()||7};e.dayOfYear=
function(a){var b=Math.round((this.clone().startOf("day")-this.clone().startOf("year"))/864E5)+1;return null==a?b:this.add(a-b,"d")};e.hour=e.hours=uc;e.minute=e.minutes=zc;e.second=e.seconds=Ac;e.millisecond=e.milliseconds=Bc;e.utcOffset=function(a,b){var c=this._offset||0,d;if(!this.isValid())return null!=a?this:NaN;if(null!=a){if("string"===typeof a){if(a=ab(Ga,a),null===a)return this}else 16>Math.abs(a)&&(a*=60);!this._isUTC&&b&&(d=15*-Math.round(this._d.getTimezoneOffset()/15));this._offset=
a;this._isUTC=!0;null!=d&&this.add(d,"m");c!==a&&(!b||this._changeInProgress?Gb(this,T(a-c,"m"),1,!1):this._changeInProgress||(this._changeInProgress=!0,g.updateOffset(this,!0),this._changeInProgress=null));return this}return this._isUTC?c:15*-Math.round(this._d.getTimezoneOffset()/15)};e.utc=function(a){return this.utcOffset(0,a)};e.local=function(a){this._isUTC&&(this.utcOffset(0,a),this._isUTC=!1,a&&this.subtract(15*-Math.round(this._d.getTimezoneOffset()/15),"m"));return this};e.parseZone=function(){if(null!=
this._tzm)this.utcOffset(this._tzm);else if("string"===typeof this._i){var a=ab(tc,this._i);null!=a?this.utcOffset(a):this.utcOffset(0,!0)}return this};e.hasAlignedHourOffset=function(a){if(!this.isValid())return!1;a=a?r(a).utcOffset():0;return 0===(this.utcOffset()-a)%60};e.isDST=function(){return this.utcOffset()>this.clone().month(0).utcOffset()||this.utcOffset()>this.clone().month(5).utcOffset()};e.isLocal=function(){return this.isValid()?!this._isUTC:!1};e.isUtcOffset=function(){return this.isValid()?
this._isUTC:!1};e.isUtc=Db;e.isUTC=Db;e.zoneAbbr=function(){return this._isUTC?"UTC":""};e.zoneName=function(){return this._isUTC?"Coordinated Universal Time":""};e.dates=C("dates accessor is deprecated. Use date instead.",Vb);e.months=C("months accessor is deprecated. Use month instead",rb);e.years=C("years accessor is deprecated. Use year instead",Tb);e.zone=C("moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/",function(a,b){return null!=a?
("string"!==typeof a&&(a=-a),this.utcOffset(a,b),this):-this.utcOffset()});e.isDSTShifted=C("isDSTShifted is deprecated. See http://momentjs.com/guides/#/warnings/dst-shifted/ for more information",function(){if(!A(this._isDSTShifted))return this._isDSTShifted;var a={};Ia(a,this);a=Ab(a);if(a._a){var b=a._isUTC?I(a._a):r(a._a);this._isDSTShifted=this.isValid()&&0<jb(a._a,b.toArray())}else this._isDSTShifted=!1;return this._isDSTShifted});var p=La.prototype;p.calendar=function(a,b,c){a=this._calendar[a]||
this._calendar.sameElse;return K(a)?a.call(b,c):a};p.longDateFormat=function(a){var b=this._longDateFormat[a],c=this._longDateFormat[a.toUpperCase()];if(b||!c)return b;this._longDateFormat[a]=c.replace(/MMMM|MM|DD|dddd/g,function(a){return a.slice(1)});return this._longDateFormat[a]};p.invalidDate=function(){return this._invalidDate};p.ordinal=function(a){return this._ordinal.replace("%d",a)};p.preparse=Kb;p.postformat=Kb;p.relativeTime=function(a,b,c,d){var e=this._relativeTime[c];return K(e)?e(a,
b,c,d):e.replace(/%d/i,a)};p.pastFuture=function(a,b){var c=this._relativeTime[0<a?"future":"past"];return K(c)?c(b):c.replace(/%s/i,b)};p.set=function(a){var b,c;for(c in a)b=a[c],K(b)?this[c]=b:this["_"+c]=b;this._config=a;this._ordinalParseLenient=new RegExp(this._ordinalParse.source+"|"+/\d{1,2}/.source)};p.months=function(a,b){return a?H(this._months)?this._months[a.month()]:this._months[(this._months.isFormat||Sb).test(b)?"format":"standalone"][a.month()]:this._months};p.monthsShort=function(a,
b){return a?H(this._monthsShort)?this._monthsShort[a.month()]:this._monthsShort[Sb.test(b)?"format":"standalone"][a.month()]:this._monthsShort};p.monthsParse=function(a,b,c){var d,e;if(this._monthsParseExact){a:{a=a.toLocaleLowerCase();if(!this._monthsParse)for(this._monthsParse=[],this._longMonthsParse=[],this._shortMonthsParse=[],d=0;12>d;++d)e=I([2E3,d]),this._shortMonthsParse[d]=this.monthsShort(e,"").toLocaleLowerCase(),this._longMonthsParse[d]=this.months(e,"").toLocaleLowerCase();if(c)b="MMM"===
b?w.call(this._shortMonthsParse,a):w.call(this._longMonthsParse,a);else if("MMM"===b){b=w.call(this._shortMonthsParse,a);if(-1!==b)break a;b=w.call(this._longMonthsParse,a)}else{b=w.call(this._longMonthsParse,a);if(-1!==b)break a;b=w.call(this._shortMonthsParse,a)}b=-1!==b?b:null}return b}this._monthsParse||(this._monthsParse=[],this._longMonthsParse=[],this._shortMonthsParse=[]);for(d=0;12>d;d++)if(e=I([2E3,d]),c&&!this._longMonthsParse[d]&&(this._longMonthsParse[d]=new RegExp("^"+this.months(e,
"").replace(".","")+"$","i"),this._shortMonthsParse[d]=new RegExp("^"+this.monthsShort(e,"").replace(".","")+"$","i")),c||this._monthsParse[d]||(e="^"+this.months(e,"")+"|^"+this.monthsShort(e,""),this._monthsParse[d]=new RegExp(e.replace(".",""),"i")),c&&"MMMM"===b&&this._longMonthsParse[d].test(a)||c&&"MMM"===b&&this._shortMonthsParse[d].test(a)||!c&&this._monthsParse[d].test(a))return d};p.monthsRegex=function(a){if(this._monthsParseExact)return u(this,"_monthsRegex")||sb.call(this),a?this._monthsStrictRegex:
this._monthsRegex;u(this,"_monthsRegex")||(this._monthsRegex=oa);return this._monthsStrictRegex&&a?this._monthsStrictRegex:this._monthsRegex};p.monthsShortRegex=function(a){if(this._monthsParseExact)return u(this,"_monthsRegex")||sb.call(this),a?this._monthsShortStrictRegex:this._monthsShortRegex;u(this,"_monthsShortRegex")||(this._monthsShortRegex=oa);return this._monthsShortStrictRegex&&a?this._monthsShortStrictRegex:this._monthsShortRegex};p.week=function(a){return ma(a,this._week.dow,this._week.doy).week};
p.firstDayOfYear=function(){return this._week.doy};p.firstDayOfWeek=function(){return this._week.dow};p.weekdays=function(a,b){return a?H(this._weekdays)?this._weekdays[a.day()]:this._weekdays[this._weekdays.isFormat.test(b)?"format":"standalone"][a.day()]:this._weekdays};p.weekdaysMin=function(a){return a?this._weekdaysMin[a.day()]:this._weekdaysMin};p.weekdaysShort=function(a){return a?this._weekdaysShort[a.day()]:this._weekdaysShort};p.weekdaysParse=function(a,b,c){var d,e;if(this._weekdaysParseExact)return cc.call(this,
a,b,c);this._weekdaysParse||(this._weekdaysParse=[],this._minWeekdaysParse=[],this._shortWeekdaysParse=[],this._fullWeekdaysParse=[]);for(d=0;7>d;d++)if(e=I([2E3,1]).day(d),c&&!this._fullWeekdaysParse[d]&&(this._fullWeekdaysParse[d]=new RegExp("^"+this.weekdays(e,"").replace(".",".?")+"$","i"),this._shortWeekdaysParse[d]=new RegExp("^"+this.weekdaysShort(e,"").replace(".",".?")+"$","i"),this._minWeekdaysParse[d]=new RegExp("^"+this.weekdaysMin(e,"").replace(".",".?")+"$","i")),this._weekdaysParse[d]||
(e="^"+this.weekdays(e,"")+"|^"+this.weekdaysShort(e,"")+"|^"+this.weekdaysMin(e,""),this._weekdaysParse[d]=new RegExp(e.replace(".",""),"i")),c&&"dddd"===b&&this._fullWeekdaysParse[d].test(a)||c&&"ddd"===b&&this._shortWeekdaysParse[d].test(a)||c&&"dd"===b&&this._minWeekdaysParse[d].test(a)||!c&&this._weekdaysParse[d].test(a))return d};p.weekdaysRegex=function(a){if(this._weekdaysParseExact)return u(this,"_weekdaysRegex")||Sa.call(this),a?this._weekdaysStrictRegex:this._weekdaysRegex;u(this,"_weekdaysRegex")||
(this._weekdaysRegex=oa);return this._weekdaysStrictRegex&&a?this._weekdaysStrictRegex:this._weekdaysRegex};p.weekdaysShortRegex=function(a){if(this._weekdaysParseExact)return u(this,"_weekdaysRegex")||Sa.call(this),a?this._weekdaysShortStrictRegex:this._weekdaysShortRegex;u(this,"_weekdaysShortRegex")||(this._weekdaysShortRegex=oa);return this._weekdaysShortStrictRegex&&a?this._weekdaysShortStrictRegex:this._weekdaysShortRegex};p.weekdaysMinRegex=function(a){if(this._weekdaysParseExact)return u(this,
"_weekdaysRegex")||Sa.call(this),a?this._weekdaysMinStrictRegex:this._weekdaysMinRegex;u(this,"_weekdaysMinRegex")||(this._weekdaysMinRegex=oa);return this._weekdaysMinStrictRegex&&a?this._weekdaysMinStrictRegex:this._weekdaysMinRegex};p.isPM=function(a){return"p"===(a+"").toLowerCase().charAt(0)};p.meridiem=function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"};ha("en",{ordinalParse:/\d{1,2}(th|st|nd|rd)/,ordinal:function(a){var b=a%10,b=1===l(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th";return a+
b}});g.lang=C("moment.lang is deprecated. Use moment.locale instead.",ha);g.langData=C("moment.langData is deprecated. Use moment.localeData instead.",S);var O=Math.abs,Cc=U("ms"),Dc=U("s"),Ec=U("m"),Fc=U("h"),Gc=U("d"),Hc=U("w"),Ic=U("M"),Jc=U("y"),Kc=ca("milliseconds"),Lc=ca("seconds"),Mc=ca("minutes"),Nc=ca("hours"),Oc=ca("days"),Pc=ca("months"),Qc=ca("years"),W=Math.round,X={s:45,m:45,h:22,d:26,M:11},db=Math.abs,m=ya.prototype;m.abs=function(){var a=this._data;this._milliseconds=O(this._milliseconds);
this._days=O(this._days);this._months=O(this._months);a.milliseconds=O(a.milliseconds);a.seconds=O(a.seconds);a.minutes=O(a.minutes);a.hours=O(a.hours);a.months=O(a.months);a.years=O(a.years);return this};m.add=function(a,b){return Mb(this,a,b,1)};m.subtract=function(a,b){return Mb(this,a,b,-1)};m.as=function(a){var b,c=this._milliseconds;a=D(a);if("month"===a||"year"===a)return b=this._days+c/864E5,b=this._months+4800*b/146097,"month"===a?b:b/12;b=this._days+Math.round(146097*this._months/4800);
switch(a){case "week":return b/7+c/6048E5;case "day":return b+c/864E5;case "hour":return 24*b+c/36E5;case "minute":return 1440*b+c/6E4;case "second":return 86400*b+c/1E3;case "millisecond":return Math.floor(864E5*b)+c;default:throw Error("Unknown unit "+a);}};m.asMilliseconds=Cc;m.asSeconds=Dc;m.asMinutes=Ec;m.asHours=Fc;m.asDays=Gc;m.asWeeks=Hc;m.asMonths=Ic;m.asYears=Jc;m.valueOf=function(){return this._milliseconds+864E5*this._days+this._months%12*2592E6+31536E6*l(this._months/12)};m._bubble=function(){var a=
this._milliseconds,b=this._days,c=this._months,d=this._data;0<=a&&0<=b&&0<=c||0>=a&&0>=b&&0>=c||(a+=864E5*Nb(146097*c/4800+b),c=b=0);d.milliseconds=a%1E3;a=B(a/1E3);d.seconds=a%60;a=B(a/60);d.minutes=a%60;a=B(a/60);d.hours=a%24;b+=B(a/24);a=B(4800*b/146097);c+=a;b-=Nb(146097*a/4800);a=B(c/12);d.days=b;d.months=c%12;d.years=a;return this};m.get=function(a){a=D(a);return this[a+"s"]()};m.milliseconds=Kc;m.seconds=Lc;m.minutes=Mc;m.hours=Nc;m.days=Oc;m.weeks=function(){return B(this.days()/7)};m.months=
Pc;m.years=Qc;m.humanize=function(a){var b=this.localeData(),c;c=!a;var d=T(this).abs(),e=W(d.as("s")),g=W(d.as("m")),h=W(d.as("h")),k=W(d.as("d")),l=W(d.as("M")),d=W(d.as("y")),e=e<X.s&&["s",e]||1>=g&&["m"]||g<X.m&&["mm",g]||1>=h&&["h"]||h<X.h&&["hh",h]||1>=k&&["d"]||k<X.d&&["dd",k]||1>=l&&["M"]||l<X.M&&["MM",l]||1>=d&&["y"]||["yy",d];e[2]=c;e[3]=0<+this;e[4]=b;c=qc.apply(null,e);a&&(c=b.pastFuture(+this,c));return b.postformat(c)};m.toISOString=Ba;m.toString=Ba;m.toJSON=Ba;m.locale=Hb;m.localeData=
Ib;m.toIsoString=C("toIsoString() is deprecated. Please use toISOString() instead (notice the capitals)",Ba);m.lang=Ub;k("X",0,0,"unix");k("x",0,0,"valueOf");h("x",Fa);h("X",/[+-]?\d+(\.\d{1,3})?/);q("X",function(a,b,c){c._d=new Date(1E3*parseFloat(a,10))});q("x",function(a,b,c){c._d=new Date(l(a))});g.version="2.17.1";gb=r;g.fn=e;g.min=function(){var a=[].slice.call(arguments,0);return Bb("isBefore",a)};g.max=function(){var a=[].slice.call(arguments,0);return Bb("isAfter",a)};g.now=function(){return Date.now?
Date.now():+new Date};g.utc=I;g.unix=function(a){return r(1E3*a)};g.months=function(a,b){return Lb(a,b,"months")};g.isDate=qa;g.locale=ha;g.invalid=ra;g.duration=T;g.isMoment=Q;g.weekdays=function(a,b,c){return cb(a,b,c,"weekdays")};g.parseZone=function(){return r.apply(null,arguments).parseZone()};g.localeData=S;g.isDuration=Za;g.monthsShort=function(a,b){return Lb(a,b,"monthsShort")};g.weekdaysMin=function(a,b,c){return cb(a,b,c,"weekdaysMin")};g.defineLocale=Ua;g.updateLocale=function(a,b){if(null!=
b){var c;c=yb;null!=v[a]&&(c=v[a]._config);b=nb(c,b);c=new La(b);c.parentLocale=v[a];v[a]=c;ha(a)}else null!=v[a]&&(null!=v[a].parentLocale?v[a]=v[a].parentLocale:null!=v[a]&&delete v[a]);return v[a]};g.locales=function(){return rc(v)};g.weekdaysShort=function(a,b,c){return cb(a,b,c,"weekdaysShort")};g.normalizeUnits=D;g.relativeTimeRounding=function(a){return void 0===a?W:"function"===typeof a?(W=a,!0):!1};g.relativeTimeThreshold=function(a,b){if(void 0===X[a])return!1;if(void 0===b)return X[a];
X[a]=b;return!0};g.calendarFormat=function(a,b){var c=a.diff(b,"days",!0);return-6>c?"sameElse":-1>c?"lastWeek":0>c?"lastDay":1>c?"sameDay":2>c?"nextDay":7>c?"nextWeek":"sameElse"};g.prototype=e;return g});

// vietnames language
moment.locale('vi', {
    months: 'Tháng Một_Tháng Hai_Tháng Ba_Tháng Tư_Tháng Năm_Tháng Sáu_Tháng Bảy_Tháng Tám_Tháng Chín_Tháng Mười_Tháng Mười Một_Tháng Mười Hai'.split('_'),
    monthsShort: 'T01_T02_T03_T04_T05_T06_T07_T08_T09_T10_T11_T12'.split('_'),
    weekdays: 'Chủ Nhật_Thứ Hai_Thứ Ba_Thứ Tư_Thứ Năm_Thứ Sáu_Thứ Bảy'.split('_'),
    weekdaysShort: 'C.Nhật_T.Hai_T.Ba_T.Tư_T.Năm_T.Sáu_T.Bảy'.split('_'),
    weekdaysMin: 'Cn_T2_T3_T4_T5_T6_T7'.split('_'),
    longDateFormat: {
        LT : 'h:mm A',
        L : 'DD/MM/YYYY',
        LL : 'D MMMM, YYYY',
        LLL : 'D MMMM, YYYY LT',
        LLLL : 'dddd, D MMMM, YYYY LT'
    },
    calendar: {
        sameDay : '[Hôm nay lúc] LT',
        nextDay : '[Ngày mai lúc] LT',
        nextWeek : 'dddd [lúc] LT',
        lastDay : '[Hôm qua lúc] LT',
        lastWeek : '[Ngày] dddd [lúc] LT',
        sameElse : 'L'
    },
    relativeTime: {
        future : 'trong %s',
        past : '%s trước',
        s : 'một vài giây trước',
        m : 'một phút trước',
        mm : '%d phút',
        h : 'một giờ trước',
        hh : '%d giờ',
        d : 'một ngày trước',
        dd : '%d ngày',
        M : 'một tháng trước',
        MM : '%d tháng',
        y : 'một năm trước',
        yy : '%d năm'
    },
    ordinal: function(number){
        return number;
    }
});

// german language
(function (moment) {
    function processRelativeTime(number, withoutSuffix, key, isFuture) {
        var format = {
            'm': ['eine Minute', 'einer Minute'],
            'h': ['eine Stunde', 'einer Stunde'],
            'd': ['ein Tag', 'einem Tag'],
            'dd': [number + ' Tage', number + ' Tagen'],
            'M': ['ein Monat', 'einem Monat'],
            'MM': [number + ' Monate', number + ' Monaten'],
            'y': ['ein Jahr', 'einem Jahr'],
            'yy': [number + ' Jahre', number + ' Jahren']
        };
        return withoutSuffix ? format[key][0] : format[key][1];
    }

    return moment.locale('de', {
        months : "Januar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November_Dezember".split("_"),
        monthsShort : "Jan._Febr._Mrz._Apr._Mai_Jun._Jul._Aug._Sept._Okt._Nov._Dez.".split("_"),
        weekdays : "Sonntag_Montag_Dienstag_Mittwoch_Donnerstag_Freitag_Samstag".split("_"),
        weekdaysShort : "So._Mo._Di._Mi._Do._Fr._Sa.".split("_"),
        weekdaysMin : "So_Mo_Di_Mi_Do_Fr_Sa".split("_"),
        longDateFormat : {
            LT: "H:mm [Uhr]",
            L : "DD.MM.YYYY",
            LL : "D. MMMM YYYY",
            LLL : "D. MMMM YYYY LT",
            LLLL : "dddd, D. MMMM YYYY LT"
        },
        calendar : {
            sameDay: "[Heute um] LT",
            sameElse: "L",
            nextDay: '[Morgen um] LT',
            nextWeek: 'dddd [um] LT',
            lastDay: '[Gestern um] LT',
            lastWeek: '[letzten] dddd [um] LT'
        },
        relativeTime : {
            future : "in %s",
            past : "vor %s",
            s : "ein paar Sekunden",
            m : processRelativeTime,
            mm : "%d Minuten",
            h : processRelativeTime,
            hh : "%d Stunden",
            d : processRelativeTime,
            dd : processRelativeTime,
            M : processRelativeTime,
            MM : processRelativeTime,
            y : processRelativeTime,
            yy : processRelativeTime
        },
        ordinal : '%d.',
        week : {
            dow : 1, // Monday is the first day of the week.
            doy : 4  // The week that contains Jan 4th is the first week of the year.
        }
    });
})(moment);

// make a shortcut to zjs
zjs.moment = moment;

// register module name, fix de tuong thich voi zjs version 1.0
if('required' in zjs)
zjs.required('moment');
})(window, zjs);